name: McMqtt
main: uk.co.electrictea.mc_mqtt.McMqtt
version: 0.0.1
website: http://electrictea.co.uk/mcpi
author: Ajtag
description: Plugin to send redstone events to an MQTT server
commands:
   mqttconnect:
      description: Connect To Server
      usage: /mqttconnect [server]
      permission: uk.co.electrictea.mc_mqtt.mqttconnect
      permission-message: You don't have uk.co.electrictea.mc_mqtt.mqttconnect
      
   mqttdisconnect:
      description: disconnect
      usage: /mqttdisconnect
      permission: uk.co.electrictea.mc_mqtt.mqttdisconnect
      permission-message: You don't have uk.co.electrictea.mc_mqtt.mqttdisconnect